name: ci/cd
on:
  pull_request:
    types: [opened, reopened, edited]
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install packages
        run: npm ci
      - name: run tests
        run: yarn test
  echo:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: echo final message
        run: echo Final
