name: Pull request
on:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install packages
        run: yarn install
      - name: run tests
        run: yarn test
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build project
        run: yarn build
